[package]
name = "tuitty"
version = "0.1.0"
authors = ["imdaveho"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(unix)'.dependencies]
libc = "0.2.51"

[dependencies]
